#!/bin/bash

mkdir ../.vim && mkdir ../.vim/swp && mkdir ../.vim/undodir
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo Run :PlugInstall to finish setup
